
services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:${POSTGRES_PORT}"
  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - minio-data:/data
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PORT: ${MINIO_PORT}
    ports:
      - "9000:${MINIO_PORT}"
      - "9090:9090"

    command: server /data --console-address ":9090"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://minio:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3

  python-app:
    build:
      context: .
    restart: always
    container_name: mock_parser
    environment:
      DISPLAY: ":99"
    depends_on:
      - minio
      - postgres_db
    command: python3 -m main_scripts.mock_user_data_scraper

