
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - minio-data:/data
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://minio:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3

  python-app:
    build:
      context: .
    restart: always
    container_name: mock_parser
    depends_on:
      - minio

